spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8080
  
eureka:
  instance:
    appname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 4693f970-e621-4286-940e-7698a59d82cc